### ISSUE TITLE
  Authorization required or not

### ISSUE THREAD

**Issue by CP3164094** [freedomikeppp/mitsubishi-cnc-m700#1]
Does the machine need authorization

**Comment by freedomikeppp** [comment]
Hello, CP3164094 .
In my case, our machine did not need authorization.
I checked the definition of IEZNcCommunication3::Open2 method in a manual,
but I was not able to find arguments like host ID and password.

**Comment by freedomikeppp** [comment]
> Does the machine need authorization

Hello, CP3164094 .
In my case, our machine did not need authorization.
I checked the definition of IEZNcCommunication3::Open2 method in a manual,
but I was not able to find arguments like host ID and password.

**Comment by CP3164094** [comment]
3Q. do u have any development help documents there

**Comment by dapeng17951** [comment]
Hello, I need FCSB1224W000-A5.zip and FCSB1224W000 Reference Manual, because I cannot register a Mitsubishi member. My email: dapeng17951@gmail.com. Thank you!

**Comment by dapeng17951** [comment]
Hello, I do not have the serial number of the FCSB1224W000-A5 product. Can you share it there? My email: dapeng17951@gmail.com. Thank you!

**Comment by xiayan830903** [comment]
Hello, I do not have the serial number of the FCSB1224W000-A5 product. Can you share it there? My email: 30615809@qq.com. Thank you!

**Comment by freedomikeppp** [comment]
I'm sorry to have kept you waiting.
I was able to find a manual.

[三菱ＣＮＣ通信用ソフトウェア　FCSB1224W000 リファレンス IB-1501208.pdf](https://github.com/freedomikeppp/mitsubishi-cnc-m700/files/4810611/FCSB1224W000.IB-1501208.pdf)

**Comment by xiayan830903** [comment]
Thank you for your reply and the manual provided. Now I have a problem that fcsb1224w000-a5 needs to enter the product ID when it is installed. I wonder if you can provide the ID information. thank you.









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "s_ikehara"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 上午8:34
收件人: "freedomikeppp/mitsubishi-cnc-m700"<mitsubishi-cnc-m700@noreply.github.com&gt;; 
抄送: "夏"<30615809@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [freedomikeppp/mitsubishi-cnc-m700]   Authorization required or not (#1)





 
I'm sorry to have kept you waiting.
 I was able to find a manual.
 
三菱ＣＮＣ通信用ソフトウェア　FCSB1224W000 リファレンス IB-1501208.pdf

**Comment by freedomikeppp** [comment]
I can't share my product ID, because that ID belongs to our company.
I'm so sorry.

**Comment by xiayan830903** [comment]
thank you&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "s_ikehara"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 上午9:18
收件人: "freedomikeppp/mitsubishi-cnc-m700"<mitsubishi-cnc-m700@noreply.github.com&gt;; 
抄送: "夏"<30615809@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [freedomikeppp/mitsubishi-cnc-m700]   Authorization required or not (#1)





 
I can't share my product ID, because that ID belongs to our company.
 I'm so sorry.

**Comment by MgenChina** [comment]
Hello, I need FCSB1224W000-A5.zip and FCSB1224W000 Reference Manual, because I cannot register a Mitsubishi member. My email: 862980268@qq.com Thank you!

**Comment by Cediddi** [comment]
I just registered to the mitsubishielectric.co.jp and downloaded FCSB1224W000 (SDK) and FCSB1224W100 (Runtime) as well as the latest version of IB(NA)1501209-F pdf file (2 revisions newer than what @freedomikeppp shared but not much is changed). It is very easy to register with google translate.

I installed FCSB1224W000 which does not require a product-id to install. I tried EZNcTest.exe and it worked. I also tried some python code and it also worked.

**Comment by 6congyao** [comment]
Hello, for FCSB1224W000 (SDK), Can you share it there? My email: 8966098@qq.com

**Comment by Cediddi** [comment]
No, that is not possible. You should download it yourself. I already
explained Google translate is your friend.

**Comment by xiayan830903** [comment]
this software need product ID，do you have it?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lu Congyao"<notifications@github.com&gt;; 
发送时间: 2020年12月28日(星期一) 下午2:52
收件人: "freedomikeppp/mitsubishi-cnc-m700"<mitsubishi-cnc-m700@noreply.github.com&gt;; 
抄送: "夏"<30615809@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [freedomikeppp/mitsubishi-cnc-m700]   Authorization required or not (#1)





 
Hello, for FCSB1224W000 (SDK), Can you share it there? My email: 8966098@qq.com

**Comment by Cediddi** [comment]
No, I don't. That's paid.

**Comment by wuxs** [comment]
hello, do you know what in a form of binary the Mitsubishi M700 returns after calling open2 to connect  the Mitsubishi M700?

**Comment by wuxs** [comment]
hello, do you know what in a form of binary the Mitsubishi M700 returns after calling open2 to connect  the Mitsubishi M700?

**Comment by Cediddi** [comment]
I only connected to M70 and M80 series with EZSocket (the afromentioned SDK), but overall workflow is the same.

EZSocket Methods always return a status code as long. 0 is S_OK aka success. Anything else is an error, all error codes exist in reference pdf. You can check part 3 of the pdf. First you should create an com object, then you should run SetTCPIPProtocol and then you should run Open2. After installing FCSB1224W000 (EZSocket) you can find a test tool named EZNcTest.exe (under C:\Program Files (x86)\EZSocket\EZSocketNc\tools path). You can use it instead of writing code.

If you search for 'FCSB1224W000 Reference Manual' in the google, you can find the PDF file without creating a mitsubishielectric.co.jp user.

**Comment by dfccdxiaogang** [comment]
Hello, I need FCSB1224W000-A5.zip and FCSB1224W000 Reference Manual, because I cannot register a Mitsubishi member. My email: 401893327@qq.com Thank you!

**Comment by gmartore** [comment]
Hello.

Somebody know where i can quote FCSB1224W000?

Thanks

**Comment by growgreat77** [comment]
Hello, I need FCSB1224W000-A5.zip  My email: 409469431@qq.com. Thank you!

**Comment by thenorhstar** [comment]
Hello,
in the function found in FCSB1224W000

**Parameter_GetData3**( 
 **lGroup As LONG** // (I) Group number
**lItem As LONG** // (I) First item number
 **lSize As LONG** // (I) Number of items
 **lAxis As LONG** // (I) Axis No.
 **pvValue As VARIANT*** // (O) Parameter value character string array
 ) **As LONG** // (O) Error code

How to use the function.  What is written in the IGroup number here?  Can you write an example command?

**Comment by GiangTuanVo** [comment]
Hi Everyone !
How to get FCSB1224W000 productID?

**Comment by ozgurklc** [comment]
Hello,
We would like to get machine running status, even under tooling change. 
Is it possible?

**Comment by isanzsuspe** [comment]
I have FCSB1224W000  but I not shure if it is possible to use it to connect to a FCA720BM-A CNC
